services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clockin_app"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - clockin-net

  backend-app:
    build:
      context: ./backend
      dockerfile: app.Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clockin-net

  backend-nginx:
    image: nginx:1.29.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - backend-app
    networks:
      - clockin-net

volumes:
  db_data:

networks:
  clockin-net:
    driver: bridge