services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clockin_app"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - clockin-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:443" # Mapea el puerto 8000 del host al 443 del contenedor
    depends_on:
      db:
        condition: service_healthy
    networks:
      - clockin-net

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    restart: always
    env_file:
      - ./.env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "443:443"
    networks:
      - clockin-net

volumes:
  db_data:

networks:
  clockin-net:
    driver: bridge