version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TuPassMySegura123!  # Contraseña simple
      POSTGRES_DB: clockin_app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - clockin-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TuPassMySegura123!  # MISMA CONTRASEÑA
      - POSTGRES_DB=clockin_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - clockin-net

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - clockin-net

volumes:
  db_data:

networks:
  clockin-net:
    driver: bridge