version: '3.8'

services: 
db:
image:postgres:15
restart: always
environmet: 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: TuPassMySegura123!
  POSTGRES_DB: clockin_app
  volumnes:
  - db_data:/var/lib/postgresql/data

backend: 
build:
  context: ./backend
  dockerfile: Dockerfile
  restart: always
  env_file:
  - .env
  ports: 
  - "8000:8000"
  depends_on: 
  - db

frontend:
  build:
  context:
  dockerfile: Dockerfile
  restart: always
  env_file: 
  - .env
  ports:
  - "3000:3000"

  volumes: 
  db_data: